### ISSUE TITLE
Fix the README.md file

### ISSUE THREAD

**Issue by NotHiiragi** [Anodyne-Js/Ano.js#2]
# Ano.js
A discord.js clone but more simple and have more features.
<div align="center">
</div>

## Example usage:
```js
const Ano = require('ano.js');
```
## Example Format:
```js
const Bot = new Ano.Bot({
  token: TOKEN, 
  prefix: PREFIX,
  owners: ['Owner_ID','Owner_ID_2']
});
```

## Commmand Format (not official)

```js

client.command({
  name: "hi",
  aliases: ['hello'],    // if none put nothing
  run {
  message.send('Hi ${message.author.username}')
  }
});
```

Note: basically none of this is official till otherwise

**Comment by NotHiiragi** [comment]
Fixed a spelling error and added 2 semicolons.

**Comment by eisabanana22** [comment]
On it
